### ISSUE TITLE
Error: Unable to open existing file

### ISSUE THREAD

**Issue by LFFATE** [vunguyentuan/vscode-css-variables#10]
Looks like my `variables.css` was recognized (autocomplete works), but I can't open it with Ctrl + Mouse Click combination. 
I see this error:
 `'variables.css': Unable to resolve resource c:/project/src/styles/variables.css.`

My OS is Windows, so maybe the issue caused by case sensitivity or slashes

**Comment by stolar-code** [comment]
I have the same issue 😶

**Comment by pangjian** [comment]
me too

**Comment by pangjian** [comment]
The file path should be 'file://c:/project/src/styles/variables.css' not 'c:/project/src/styles/variables.css'
