### ISSUE TITLE
Autocomplete duplication

### ISSUE THREAD

**Issue by LFFATE** [vunguyentuan/vscode-css-variables#11]
For example, if I type: 
`margin-bottom: var(`
then double dash `--` VSCode offer me available variables. And if I select one I see these result:
`margin-bottom: var(----common-margin`
and in case I type part of a variable:
`margin-bottom: var(--common` then select a prompt:
`margin-bottom: var(--common--common-margin`
![css_variables](https://user-images.githubusercontent.com/3839490/148902742-1d4946d8-644b-471d-b47a-43c0af57059e.gif)

**Comment by mthines** [comment]
Hey.

I agree there's an issue with the plugin when you use it inside another `var`, but to me it also looks like you're overthinking it?

You use the plugin to save time from writing `var` and you get the intelligesense

Check out below it is recommended to be used. ⬇️

![usage](https://user-images.githubusercontent.com/16097850/152416675-a4061ef8-a81a-4ec9-aec9-55913790ab7f.gif)

In this case i use [Emmet](https://docs.emmet.io/cheat-sheet/) `fz` to autocomplete `font-size`, and then write `--` following the variable I want to use (in this case `--fz-42`.

That adds the variable and creates the `var()` for you. Much easier :)
