### ISSUE TITLE
Settings do nothing

### ISSUE THREAD

**Issue by hipstersmoothie** [vunguyentuan/vscode-css-variables#12]
I played around with the include/exclude settings a bunch and they aren't doing anything. I've also restarted vscode to try to make it work to no effect.

With these settings I would expect no autocompletion to happen

```json
"cssVariables.lookupFiles": [],
"cssVariables.blacklistFolders": ["**/*.css"]
```

**Comment by mrtamagotchi** [comment]
I have the same issue.

**Comment by mafte** [comment]
I have the same problem.

Thanks for this great extension.

**Comment by bakura10** [comment]
Hello,

I'm experiencing the same issue. With the same config I would expect to not have autocomplete, but for some reason the extension insists on scanning a file in my dist/assets folder (which, if I undersand, should be ignored by default).

Is the extension somehow forcing some files to be scanned despite being blacklisted?
