### ISSUE TITLE
Cross publish extension to Open VSX

### ISSUE THREAD

**Issue by maiertech** [vunguyentuan/vscode-css-variables#16]
Would you mind considering cross-publishing vscode-css-variables to https://open-vsx.org/?

I do most of my development on https://www.gitpod.io/ and from within their VS Code I do not have access to the VS Code marketplace, only Open VSX. 

You can find more information on how to publish your extension to Open VSX here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

**Comment by vunguyentuan** [comment]
Here you go https://open-vsx.org/extension/vunguyentuan/vscode-css-variables

**Comment by maiertech** [comment]
So cool, thank you @vunguyentuan!
