### ISSUE TITLE
tailwind support

### ISSUE THREAD

**Issue by diminutivesloop** [vunguyentuan/vscode-css-variables#17]
I'm working on a project that uses [Tailwind](https://tailwindcss.com/) for styling and it defines most of its css variables in a `tailwind.css` file which uses special [tailwind-specific directives](https://tailwindcss.com/docs/functions-and-directives) such as `@apply` and `@layer`. Currently the only way to get this extension to recognize the css variable declarations in that file is to remove those special directives. It would be great if this extension could be updated to detect variables even when they're nested inside these directives.

**Comment by vunguyentuan** [comment]
@diminutivesloop you should be able to use it now in the latest version

**Comment by diminutivesloop** [comment]
Thanks so much! Now while I am getting auto-complete w/ color preview for all the variables in the `tawilwind.css` file there are a few remaining issues.
- The color preview swatch shows up in the autocomplete list and for any regular variable definitions, but it doesn't show for variable definitions within the `@apply` directive. I can open another ticket for this if you'd like.
- I get duplicate suggestions for any variables that are already used within the current file, but those suggestions don't have the color preview. It's a minor issue, but do you happen to know of any way to disable these suggestions or de-prioritize them?
