### ISSUE TITLE
VSCode `suggest` - suggestions in weird places

### ISSUE THREAD

**Issue by mthines** [vunguyentuan/vscode-css-variables#2]
Hey again @vunguyentuan.
Sorry for bothering again, but I see great potential in your extension.

I got an issue regarding when trying to destructure an property from a JS object in Typescript.

As you can see in the gifs below, there's for sure no need to get css variables suggestions when destructuring an object.

Is this something you can fix so it's only in markup places?
Or even just allow users to select which files the suggestion should work in so I could choce scss/css alone.

#### A - With the extension enabled
![Current Behavior](https://user-images.githubusercontent.com/16097850/103537459-be506c00-4e94-11eb-95ed-70228892a554.gif)

#### B - With the extension disabled
![Expected](https://user-images.githubusercontent.com/16097850/103537471-c27c8980-4e94-11eb-943b-bafec07c1fae.gif)

Thanks!

**Comment by vunguyentuan** [comment]
@mthines I just published new version that fixed your issue, please check it if you have time :D

**Comment by mthines** [comment]
This has been fixed as well.
Awesome mate. Good job
