### ISSUE TITLE
Deleted variables still appears

### ISSUE THREAD

**Issue by GB2101** [vunguyentuan/vscode-css-variables#25]
After I delete the variable declaration, it still appears on the list of variables. Only after reloading the page it gets the correct list.
It is mainly noticeable when I rename a variable, and both the old name and new one are shown.

**Comment by mthines** [comment]
@GB2101 

As much as I don't agree it's ideal, restarting VSCode solved the problem from me :) 

There should be a command to clear the cache, restart the server or something like that.

**Comment by vunguyentuan** [comment]
Latest version fixed this issue 

2.3.11
--


<br class="Apple-interchange-newline">

https://marketplace.visualstudio.com/items?itemName=vunguyentuan.vscode-css-variables
