### ISSUE TITLE
Ability to add locations

### ISSUE THREAD

**Issue by djmtype** [vunguyentuan/vscode-css-variables#28]
By ignoring `"**/node_modules"` location, this plugin can't search custom props within frameworks like Open-Props. 

Choosing to ignore node_modules is smart for obvious reasons, but please allow for certain overrides to access specific packages within node_modules.

**Comment by vunguyentuan** [comment]
This is how I setup
```json
{
  "cssVariables.lookupFiles": [
    "**/*.css",
    "**/*.scss",
    "**/*.sass",
    "**/*.less",
    "node_modules/open-props/open-props.min.css"
  ]
}

```

You can checkout my test project with open-props here https://github.com/vunguyentuan/test-css-var
and please update the extension to the latest version 2.3.11
