### ISSUE TITLE
Path error in VSCode console

### ISSUE THREAD

**Issue by wilsoniwano** [vunguyentuan/vscode-css-variables#3]
Hi @vunguyentuan.

You will save our lives with this plugin. 😁

But I'm getting a console error in Windows:
`console.ts:137 [Extension Host] trigger     buty {triggerKind: 0}triggerKind: 0__proto__: Object
log.ts:197   ERR ENOENT: no such file or directory, open '\c%3A\Projetos\test\variables.css': Error: ENOENT: no such file or directory, open '\c%3A\Projetos\test\variables.css'`

The settings.json is like this:
`{
    "cssVariables.lookupFiles": [
        "variables.css"
    ]
}`

This is my folder structure:
![image](https://user-images.githubusercontent.com/9750705/104526501-f06e7600-55d8-11eb-8621-5b093f5b35cf.png)

Could you help us?

**Comment by vunguyentuan** [comment]
I will check it tonight with my PC 👍

**Comment by vunguyentuan** [comment]
@wilsoniwano There was a mistake to get workspace path, I just fixed that and published new version 1.4.3

**Comment by wilsoniwano** [comment]
It's working perfectly now! Thank you very much! 👍🙌🎉
