### ISSUE TITLE
How to include external css package located in node_modules?

### ISSUE THREAD

**Issue by obriankevin11** [vunguyentuan/vscode-css-variables#45]
Hi,

I have an external npm package that provides collections of variables. How can I include them in the vscode extension?

Thank you.

**Comment by vunguyentuan** [comment]
Hi @obriankevin11, you can update your `.vscode/settings.json` like this

**.vscode/settings.json**
```json
{
  "cssVariables.lookupFiles": [
    "**/*.css",
    "**/*.scss",
    "**/*.sass",
    "**/*.less",
    "node_modules/open-props/open-props.min.css"
  ]
}
```

**Comment by obriankevin11** [comment]
Oops, looks like I was in a bad day it's in the main page...sorry
