### ISSUE TITLE
Preview colors inline

### ISSUE THREAD

**Issue by nighto** [vunguyentuan/vscode-css-variables#5]
It'd be great if it would show the variable color preview not only in the dropdown menu, but directly in the code like it does with hardcoded colors, i.e. that small square:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/397851/119268107-5d2df880-bbe9-11eb-8dc7-3f687a4459d6.png">

**Comment by vunguyentuan** [comment]
Available on new version v2.3.0
<img width="810" alt="image" src="https://user-images.githubusercontent.com/7245986/147893795-dcfcb708-29df-4a91-ac05-5a7239f0e227.png">

**Comment by manjunath-teachmint** [comment]
this is not visible when  I use variable from node_modules
