### ISSUE TITLE
Generating config file!

### ISSUE THREAD

**Issue by flamurbeqiraj** [vunguyentuan/vscode-css-variables#6]
When it comes to the configuration, its quite easy but it takes wasted time. I would suggest to use the: Command Palette, which the user can activate on the shortcut: "CTRL + SHIFT + P", and than search there for: "CSS V.A Config" or whatever you will name it. After clicking on it, it should create the folder ".vscode" if it's missing, and the file "settings.json" if it's missing, with a written template sample, which everybody can configure however they want later. + Additional idea, after clicking the command from the palette, it would be nice the setting.json file to be opened in the editor.

With all my respect :).

**Comment by vunguyentuan** [comment]
@flamurbeqiraj I've published a new version 2, no need configuration file
