### ISSUE TITLE
Allow CDN links in lookupFiles list

### ISSUE THREAD

**Issue by Rod911** [vunguyentuan/vscode-css-variables#61]
Usually I add the cdn link in the html of the project instead of using @import to help with performance, I tried adding the link in cssVariables.lookupFiles config but it doesn't seem to generate any suggessions for those. Is it a bug or not part of the extension yet?

**Comment by vunguyentuan** [comment]
Hi @Rod911, its not part of the extension yet.

I think it is a good suggestion, when I implement @import feature I never thought about I can support import from URL directly from the lookupFiles config

Will support it in the next release

Thank you!
