### ISSUE TITLE
[Bug] Accepting autocomplete is problematic in daily use

### ISSUE THREAD

**Issue by yhnavein** [vunguyentuan/vscode-css-variables#63]
Take a look on the video what I am struggling on a daily basis with this extension:

https://user-images.githubusercontent.com/516709/218255211-c891b543-fe77-431d-b5f7-66ce0147b433.mov

Two main problems here to observe:
1. Typing `var(` wrongly produces `var()()`
2. Selecting a color from the autocomplete list prefixes it with 1 (sometimes 2) additional dashes.

Additionally (not on the video) if you started typing full color name with dashes (without `var`) and then selected something from the list then you will end with something like this: `-var(--colorAccent)` which is not correct as well.

I am using your plugin in JSX / TSX code only.

**Comment by vunguyentuan** [comment]
@yhnavein I understand your frustration but your first problem is coming from [vscode-styled-components](https://github.com/styled-components/vscode-styled-components) itself.

https://github.com/styled-components/vscode-styled-components/issues/379

For second problem, I suspect it also coming from vscode-styled-components extension, as the extension still working fine on svelte, astro, vue, and css files

You can verify it by uninstall this extension and try again.
